version: "3"

volumes:
  scm-db:

services:
  scm-db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret_pw
      - MYSQL_USER=scm-admin
      - MYSQL_PASSWORD=secret-scm-pw
      - MYSQL_DATABASE=simpleclubmanager
    volumes:
      - scm-db:/var/lib/mysql
  scm-web:
    build: ./
    image: scm
    depends_on:
      - scm-db
    links:
      - scm-db
    labels:
      - "traefik.enable=true"
      - "traefik.backend=scm"
      - "traefik.port=8000"
      - "traefik.frontend.rule=Host:simpleclubmanager.ch"
  proxy:
    image: traefik:alpine
    command: "--docker --docker.domain=simpleclubmanager.ch --logLevel=DEBUG"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /project/traefik/acme.json:/acme.json
      - /project/traefik/traefik.toml:/traefik.toml
      - /project/traefik/log:/log
