version: "3"

volumes:
  scm-db:

services:
  scm-db-server:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret_pw
      - MYSQL_USER=scm-admin
      - MYSQL_PASSWORD=secret-scm-pw
      - MYSQL_DATABASE=simpleclubmanager
    ports:
      - 3306:3306
    volumes:
      - scm-db:/var/lib/mysql