version: "3"

volumes:
  scm-db:

services:
  scm-db:
    image: mariadb
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=secret_pw
      - MYSQL_USER=scm-admin
      - MYSQL_PASSWORD=secret-scm-pw
      - MYSQL_DATABASE=simpleclubmanager
    ports:
      - 3306:3306
    volumes:
      - scm-db:/var/lib/mysql
  scm-web:
    image: izolight/scm:0.3
    depends_on:
      - scm-db
    links:
      - scm-db
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
