from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^member/add/$', views.add_member, name='add_member'),
    url(r'^member/list/$', views.list_member, name='list_member'),
    url(r'^member/delete/', views.delete_member),
    url(r'^member/edit/', views.edit_member),
    url(r'^bill/list/', views.list_bill),
    url(r'^bill/open/', views.open_bill),
    url(r'^bill/facturate/', views.facturate_bill),
    url(r'^bill/facturated/', views.facturated_bill),
    url(r'^bill/delayed/', views.delayed_bill),
    url(r'^bill/reminded/', views.reminded_bill),
    url(r'^bill/register/', views.register_bill),
    url(r'^bill/notpayed/', views.notpayed_bill),
    url(r'^contact/', views.contact),
    url(r'^ice/plan/', views.plan_ice),
    url(r'^ice/add/', views.add_ice),
    url(r'^ice/edit/', views.edit_ice),
    url(r'^ice/delete/', views.delete_ice),
    url(r'^impressum/', views.impressum),
    url(r'^login/', views.login),
    url(r'^material/list/', views.list_material),
    url(r'^material/add/', views.add_material),
    url(r'^material/edit/', views.edit_material),
    url(r'^material/reservate/', views.reservate_material),
    url(r'^material/delete/', views.delete_material),
    url(r'^training/list/', views.list_training),
    url(r'^training/add', views.add_training),
    url(r'^training/edit', views.edit_training),
    url(r'^training/delete', views.delete_training),

]
