# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 18:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('main_app', '0003_auto_20171018_1821'), ('main_app', '0004_auto_20171018_1841'), ('main_app', '0005_auto_20171018_1844')]

    dependencies = [
        ('main_app', '0002_auto_20171018_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='main_app.City'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Bitte gültige Telefonnummer eingeben', regex='^\\+41\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
