# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_PLZ-Fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main_app.City'),
        ),
    ]
