# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20171129_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(to='main_app.Member'),
        ),
        migrations.AddField(
            model_name='iceslot',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Club'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Member'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Invoice'),
        ),
        migrations.AddField(
            model_name='training',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Club'),
        ),
        migrations.AddField(
            model_name='training',
            name='ice_slot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.IceSlot'),
        ),
        migrations.AddField(
            model_name='training',
            name='members',
            field=models.ManyToManyField(to='main_app.Member'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.SubscriptionType'),
        ),
    ]
