# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20171201_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user_name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings_as_trainer', to='main_app.Member'),
        ),
        migrations.AlterField(
            model_name='training',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='main_app.Club'),
        ),
        migrations.AlterField(
            model_name='training',
            name='ice_slot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.IceSlot'),
        ),
        migrations.AlterField(
            model_name='training',
            name='members',
            field=models.ManyToManyField(related_name='trainings', to='main_app.Member'),
        ),
    ]
