# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20171208_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iceslot',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ice_slots', to='main_app.Club'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='main_app.Member'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='main_app.Invoice'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='main_app.SubscriptionType'),
        ),
        migrations.AlterField(
            model_name='training',
            name='ice_slot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='main_app.IceSlot'),
        ),
    ]
