# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20171208_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iceslot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='iceslot',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
