# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20171208_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='members',
        ),
        migrations.AddField(
            model_name='member',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='main_app.Club'),
        ),
    ]
