# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20171208_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
