# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20171215_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='invoice',
        ),
    ]
