# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20171220_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='main_app.Invoice'),
        ),
    ]
