# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20171220_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='main_app.Member'),
        ),
    ]
