# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20171220_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='ice_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='main_app.IceSlot'),
        ),
    ]
